/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FSAE_FSAE_TELEMETRY_PB_H_INCLUDED
#define PB_FSAE_FSAE_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _fsae_BatteryModule {
    uint32_t module_id;
    /* 23 节电芯电压 */
    uint32_t v01;
    uint32_t v02;
    uint32_t v03;
    uint32_t v04;
    uint32_t v05;
    uint32_t v06;
    uint32_t v07;
    uint32_t v08;
    uint32_t v09;
    uint32_t v10;
    uint32_t v11;
    uint32_t v12;
    uint32_t v13;
    uint32_t v14;
    uint32_t v15;
    uint32_t v16;
    uint32_t v17;
    uint32_t v18;
    uint32_t v19;
    uint32_t v20;
    uint32_t v21;
    uint32_t v22;
    uint32_t v23;
    /* 8 个温度 */
    int32_t t1;
    int32_t t2;
    int32_t t3;
    int32_t t4;
    int32_t t5;
    int32_t t6;
    int32_t t7;
    int32_t t8;
} fsae_BatteryModule;

typedef struct _fsae_TelemetryFrame {
    /* --- 1. 基础信息 --- */
    uint32_t timestamp_ms;
    uint32_t frame_id;
    /* --- 2. 驾驶员输入 --- */
    float apps_position;
    float brake_pressure;
    float steering_angle;
    /* --- 3. 高压系统 --- */
    float hv_voltage;
    float hv_current;
    float battery_temp_max;
    uint32_t fault_code;
    /* --- 4. 动力系统 --- */
    int32_t motor_rpm;
    float motor_temp;
    float inverter_temp;
    /* --- 5. 车辆状态 (改为整数：0=Off, 1=On) --- */
    uint32_t ready_to_drive;
    uint32_t vcu_status;
    /* --- 6. BMS 详细数据 */
    pb_size_t modules_count;
    fsae_BatteryModule modules[6];
    /* --- 7. 电池包摘要（带宽受限，仅保留上云必需量） */
    uint32_t battery_soc;
    uint32_t max_cell_voltage;
    uint32_t min_cell_voltage;
    uint32_t max_cell_voltage_no;
    uint32_t min_cell_voltage_no;
    int32_t max_temp;
    int32_t min_temp;
    uint32_t max_temp_no;
    uint32_t min_temp_no;
    /* --- 8. 简化故障字 */
    uint32_t battery_fault_code;
} fsae_TelemetryFrame;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define fsae_BatteryModule_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define fsae_TelemetryFrame_init_default         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default, fsae_BatteryModule_init_default}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define fsae_BatteryModule_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define fsae_TelemetryFrame_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero, fsae_BatteryModule_init_zero}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define fsae_BatteryModule_module_id_tag         1
#define fsae_BatteryModule_v01_tag               2
#define fsae_BatteryModule_v02_tag               3
#define fsae_BatteryModule_v03_tag               4
#define fsae_BatteryModule_v04_tag               5
#define fsae_BatteryModule_v05_tag               6
#define fsae_BatteryModule_v06_tag               7
#define fsae_BatteryModule_v07_tag               8
#define fsae_BatteryModule_v08_tag               9
#define fsae_BatteryModule_v09_tag               10
#define fsae_BatteryModule_v10_tag               11
#define fsae_BatteryModule_v11_tag               12
#define fsae_BatteryModule_v12_tag               13
#define fsae_BatteryModule_v13_tag               14
#define fsae_BatteryModule_v14_tag               15
#define fsae_BatteryModule_v15_tag               16
#define fsae_BatteryModule_v16_tag               17
#define fsae_BatteryModule_v17_tag               18
#define fsae_BatteryModule_v18_tag               19
#define fsae_BatteryModule_v19_tag               20
#define fsae_BatteryModule_v20_tag               21
#define fsae_BatteryModule_v21_tag               22
#define fsae_BatteryModule_v22_tag               23
#define fsae_BatteryModule_v23_tag               24
#define fsae_BatteryModule_t1_tag                30
#define fsae_BatteryModule_t2_tag                31
#define fsae_BatteryModule_t3_tag                32
#define fsae_BatteryModule_t4_tag                33
#define fsae_BatteryModule_t5_tag                34
#define fsae_BatteryModule_t6_tag                35
#define fsae_BatteryModule_t7_tag                36
#define fsae_BatteryModule_t8_tag                37
#define fsae_TelemetryFrame_timestamp_ms_tag     1
#define fsae_TelemetryFrame_frame_id_tag         2
#define fsae_TelemetryFrame_apps_position_tag    3
#define fsae_TelemetryFrame_brake_pressure_tag   4
#define fsae_TelemetryFrame_steering_angle_tag   5
#define fsae_TelemetryFrame_hv_voltage_tag       6
#define fsae_TelemetryFrame_hv_current_tag       7
#define fsae_TelemetryFrame_battery_temp_max_tag 8
#define fsae_TelemetryFrame_fault_code_tag       9
#define fsae_TelemetryFrame_motor_rpm_tag        10
#define fsae_TelemetryFrame_motor_temp_tag       11
#define fsae_TelemetryFrame_inverter_temp_tag    12
#define fsae_TelemetryFrame_ready_to_drive_tag   13
#define fsae_TelemetryFrame_vcu_status_tag       14
#define fsae_TelemetryFrame_modules_tag          15
#define fsae_TelemetryFrame_battery_soc_tag      16
#define fsae_TelemetryFrame_max_cell_voltage_tag 17
#define fsae_TelemetryFrame_min_cell_voltage_tag 18
#define fsae_TelemetryFrame_max_cell_voltage_no_tag 19
#define fsae_TelemetryFrame_min_cell_voltage_no_tag 20
#define fsae_TelemetryFrame_max_temp_tag         21
#define fsae_TelemetryFrame_min_temp_tag         22
#define fsae_TelemetryFrame_max_temp_no_tag      23
#define fsae_TelemetryFrame_min_temp_no_tag      24
#define fsae_TelemetryFrame_battery_fault_code_tag 25

/* Struct field encoding specification for nanopb */
#define fsae_BatteryModule_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   module_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   v01,               2) \
X(a, STATIC,   SINGULAR, UINT32,   v02,               3) \
X(a, STATIC,   SINGULAR, UINT32,   v03,               4) \
X(a, STATIC,   SINGULAR, UINT32,   v04,               5) \
X(a, STATIC,   SINGULAR, UINT32,   v05,               6) \
X(a, STATIC,   SINGULAR, UINT32,   v06,               7) \
X(a, STATIC,   SINGULAR, UINT32,   v07,               8) \
X(a, STATIC,   SINGULAR, UINT32,   v08,               9) \
X(a, STATIC,   SINGULAR, UINT32,   v09,              10) \
X(a, STATIC,   SINGULAR, UINT32,   v10,              11) \
X(a, STATIC,   SINGULAR, UINT32,   v11,              12) \
X(a, STATIC,   SINGULAR, UINT32,   v12,              13) \
X(a, STATIC,   SINGULAR, UINT32,   v13,              14) \
X(a, STATIC,   SINGULAR, UINT32,   v14,              15) \
X(a, STATIC,   SINGULAR, UINT32,   v15,              16) \
X(a, STATIC,   SINGULAR, UINT32,   v16,              17) \
X(a, STATIC,   SINGULAR, UINT32,   v17,              18) \
X(a, STATIC,   SINGULAR, UINT32,   v18,              19) \
X(a, STATIC,   SINGULAR, UINT32,   v19,              20) \
X(a, STATIC,   SINGULAR, UINT32,   v20,              21) \
X(a, STATIC,   SINGULAR, UINT32,   v21,              22) \
X(a, STATIC,   SINGULAR, UINT32,   v22,              23) \
X(a, STATIC,   SINGULAR, UINT32,   v23,              24) \
X(a, STATIC,   SINGULAR, SINT32,   t1,               30) \
X(a, STATIC,   SINGULAR, SINT32,   t2,               31) \
X(a, STATIC,   SINGULAR, SINT32,   t3,               32) \
X(a, STATIC,   SINGULAR, SINT32,   t4,               33) \
X(a, STATIC,   SINGULAR, SINT32,   t5,               34) \
X(a, STATIC,   SINGULAR, SINT32,   t6,               35) \
X(a, STATIC,   SINGULAR, SINT32,   t7,               36) \
X(a, STATIC,   SINGULAR, SINT32,   t8,               37)
#define fsae_BatteryModule_CALLBACK NULL
#define fsae_BatteryModule_DEFAULT NULL

#define fsae_TelemetryFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_id,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    apps_position,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    brake_pressure,    4) \
X(a, STATIC,   SINGULAR, FLOAT,    steering_angle,    5) \
X(a, STATIC,   SINGULAR, FLOAT,    hv_voltage,        6) \
X(a, STATIC,   SINGULAR, FLOAT,    hv_current,        7) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_temp_max,   8) \
X(a, STATIC,   SINGULAR, UINT32,   fault_code,        9) \
X(a, STATIC,   SINGULAR, INT32,    motor_rpm,        10) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_temp,       11) \
X(a, STATIC,   SINGULAR, FLOAT,    inverter_temp,    12) \
X(a, STATIC,   SINGULAR, UINT32,   ready_to_drive,   13) \
X(a, STATIC,   SINGULAR, UINT32,   vcu_status,       14) \
X(a, STATIC,   REPEATED, MESSAGE,  modules,          15) \
X(a, STATIC,   SINGULAR, UINT32,   battery_soc,      16) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_voltage,  17) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_voltage,  18) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_voltage_no,  19) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_voltage_no,  20) \
X(a, STATIC,   SINGULAR, SINT32,   max_temp,         21) \
X(a, STATIC,   SINGULAR, SINT32,   min_temp,         22) \
X(a, STATIC,   SINGULAR, UINT32,   max_temp_no,      23) \
X(a, STATIC,   SINGULAR, UINT32,   min_temp_no,      24) \
X(a, STATIC,   SINGULAR, UINT32,   battery_fault_code,  25)
#define fsae_TelemetryFrame_CALLBACK NULL
#define fsae_TelemetryFrame_DEFAULT NULL
#define fsae_TelemetryFrame_modules_MSGTYPE fsae_BatteryModule

extern const pb_msgdesc_t fsae_BatteryModule_msg;
extern const pb_msgdesc_t fsae_TelemetryFrame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fsae_BatteryModule_fields &fsae_BatteryModule_msg
#define fsae_TelemetryFrame_fields &fsae_TelemetryFrame_msg

/* Maximum encoded size of messages (where known) */
#define FSAE_FSAE_TELEMETRY_PB_H_MAX_SIZE        fsae_TelemetryFrame_size
#define fsae_BatteryModule_size                  209
#define fsae_TelemetryFrame_size                 1423

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
